CREATE TABLE "public"."aluno" (
  "id"                bigint                   GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "criado_em"         timestamp with time zone NOT NULL DEFAULT now(),
  "campi_id"          bigint                   NOT NULL,
  "nome"              character varying        NOT NULL,
  "sobrenome"         character varying,
  "ra"                character varying,
  "foto_perfil_url"   text,
  "curso_id"          bigint                   NOT NULL,
  "ano_ingresso"      smallint                 NOT NULL,
  "semestre_ingresso" smallint,
  CONSTRAINT "aluno_pkey" PRIMARY KEY (id)
);

ALTER TABLE "public"."aluno"
  ENABLE ROW LEVEL SECURITY;

CREATE TABLE "public"."campi" (
  "id"              bigint                   GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "criado_em"       timestamp with time zone NOT NULL DEFAULT now(),
  "universidade_id" bigint                   NOT NULL,
  "nome"            character varying,
  "cidade"          character varying,
  "estado"          character varying,
  "endereço"        text,
  "logo_url"        text,
  CONSTRAINT "campi_pkey" PRIMARY KEY (id)
);

ALTER TABLE "public"."campi"
  ENABLE ROW LEVEL SECURITY;

CREATE TABLE "public"."curso" (
  "id"        bigint                   GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "criado_em" timestamp with time zone NOT NULL DEFAULT now(),
  "camp_id"   bigint                   NOT NULL,
  "nome"      character varying        NOT NULL,
  "sigla"     character varying,
  "descricao" text,
  CONSTRAINT "curso_pkey" PRIMARY KEY (id)
);

ALTER TABLE "public"."curso"
  ENABLE ROW LEVEL SECURITY;

CREATE TABLE "public"."universidade" (
  "id"           bigint                   GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "criado_em"    timestamp with time zone NOT NULL DEFAULT now(),
  "nome"         character varying,
  "sigla"        character varying,
  "logo_url"     text,
  "banner_url"   text,
  "site_oficial" character varying,
  CONSTRAINT "universidade_pkey" PRIMARY KEY (id)
);

ALTER TABLE "public"."universidade"
  ENABLE ROW LEVEL SECURITY;

ALTER TABLE "public"."aluno"
  ADD CONSTRAINT "aluno_campi_id_fkey" FOREIGN KEY (campi_id) REFERENCES public.campi(id) ON UPDATE RESTRICT ON DELETE RESTRICT;

ALTER TABLE "public"."curso"
  ADD CONSTRAINT "curso_camp_id_fkey" FOREIGN KEY (camp_id) REFERENCES public.campi(id);

ALTER TABLE "public"."aluno"
  ADD CONSTRAINT "aluno_curso_id_fkey" FOREIGN KEY (curso_id) REFERENCES public.curso(id) ON UPDATE RESTRICT ON DELETE RESTRICT;

ALTER TABLE "public"."campi"
  ADD CONSTRAINT "campi_universidade_id_fkey" FOREIGN KEY (universidade_id) REFERENCES public.universidade(id) ON UPDATE RESTRICT ON DELETE RESTRICT;

COMMENT ON TABLE "public"."aluno" IS 'Aluno pertencente a uma faculdade';

COMMENT ON TABLE "public"."campi" IS 'Unidade dentro da faculdade/instituição';

COMMENT ON TABLE "public"."curso" IS 'Curso de uma faculdade';

COMMENT ON TABLE "public"."universidade" IS 'Faculdade ou instituição';

REVOKE ALL ON SEQUENCE "public"."aluno_id_seq" FROM "anon";

GRANT SELECT, UPDATE, USAGE ON SEQUENCE "public"."aluno_id_seq" TO "anon";

REVOKE ALL ON SEQUENCE "public"."aluno_id_seq" FROM "authenticated";

GRANT SELECT, UPDATE, USAGE ON SEQUENCE "public"."aluno_id_seq" TO "authenticated";

REVOKE ALL ON SEQUENCE "public"."aluno_id_seq" FROM "postgres";

GRANT SELECT, UPDATE, USAGE ON SEQUENCE "public"."aluno_id_seq" TO "postgres";

REVOKE ALL ON SEQUENCE "public"."aluno_id_seq" FROM "service_role";

GRANT SELECT, UPDATE, USAGE ON SEQUENCE "public"."aluno_id_seq" TO "service_role";

REVOKE ALL ON SEQUENCE "public"."campi_id_seq" FROM "anon";

GRANT SELECT, UPDATE, USAGE ON SEQUENCE "public"."campi_id_seq" TO "anon";

REVOKE ALL ON SEQUENCE "public"."campi_id_seq" FROM "authenticated";

GRANT SELECT, UPDATE, USAGE ON SEQUENCE "public"."campi_id_seq" TO "authenticated";

REVOKE ALL ON SEQUENCE "public"."campi_id_seq" FROM "postgres";

GRANT SELECT, UPDATE, USAGE ON SEQUENCE "public"."campi_id_seq" TO "postgres";

REVOKE ALL ON SEQUENCE "public"."campi_id_seq" FROM "service_role";

GRANT SELECT, UPDATE, USAGE ON SEQUENCE "public"."campi_id_seq" TO "service_role";

REVOKE ALL ON SEQUENCE "public"."curso_id_seq" FROM "anon";

GRANT SELECT, UPDATE, USAGE ON SEQUENCE "public"."curso_id_seq" TO "anon";

REVOKE ALL ON SEQUENCE "public"."curso_id_seq" FROM "authenticated";

GRANT SELECT, UPDATE, USAGE ON SEQUENCE "public"."curso_id_seq" TO "authenticated";

REVOKE ALL ON SEQUENCE "public"."curso_id_seq" FROM "postgres";

GRANT SELECT, UPDATE, USAGE ON SEQUENCE "public"."curso_id_seq" TO "postgres";

REVOKE ALL ON SEQUENCE "public"."curso_id_seq" FROM "service_role";

GRANT SELECT, UPDATE, USAGE ON SEQUENCE "public"."curso_id_seq" TO "service_role";

REVOKE ALL ON SEQUENCE "public"."universidade_id_seq" FROM "anon";

GRANT SELECT, UPDATE, USAGE ON SEQUENCE "public"."universidade_id_seq" TO "anon";

REVOKE ALL ON SEQUENCE "public"."universidade_id_seq" FROM "authenticated";

GRANT SELECT, UPDATE, USAGE ON SEQUENCE "public"."universidade_id_seq" TO "authenticated";

REVOKE ALL ON SEQUENCE "public"."universidade_id_seq" FROM "postgres";

GRANT SELECT, UPDATE, USAGE ON SEQUENCE "public"."universidade_id_seq" TO "postgres";

REVOKE ALL ON SEQUENCE "public"."universidade_id_seq" FROM "service_role";

GRANT SELECT, UPDATE, USAGE ON SEQUENCE "public"."universidade_id_seq" TO "service_role";

GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE "public"."aluno" TO "anon", "authenticated";

REVOKE ALL ON TABLE "public"."aluno" FROM "postgres";

GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE "public"."aluno" TO "postgres";

GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE "public"."aluno" TO "service_role";

GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE "public"."campi" TO "anon", "authenticated";

REVOKE ALL ON TABLE "public"."campi" FROM "postgres";

GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE "public"."campi" TO "postgres";

GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE "public"."campi" TO "service_role";

GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE "public"."curso" TO "anon", "authenticated";

REVOKE ALL ON TABLE "public"."curso" FROM "postgres";

GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE "public"."curso" TO "postgres";

GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE "public"."curso" TO "service_role";

GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE "public"."universidade" TO "anon", "authenticated";

REVOKE ALL ON TABLE "public"."universidade" FROM "postgres";

GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE "public"."universidade" TO "postgres";

GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE "public"."universidade" TO "service_role";

